import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearchParams, Link } from 'react-router-dom';
import { useAuthStore } from '../stores/authStore';
import toast from 'react-hot-toast';
import { Eye, EyeOff } from 'lucide-react';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { doc, setDoc, collection, serverTimestamp } from 'firebase/firestore';
import { auth, db } from '../firebase';
import { CURRENCY_OPTIONS } from '../utils/formatCurrency';

export default function Login() {
  const { t } = useTranslation();
  const [searchParams] = useSearchParams();
  const { loginWithEmail, loginWithPin, loading, error, clearError } = useAuthStore();
  // Derive initial mode from URL query param at mount — no useEffect needed
  const [mode, setMode] = useState(() => {
    const queryMode = searchParams.get('mode');
    if (queryMode === 'register' || queryMode === 'pin' || queryMode === 'email') {
      return queryMode;
    }
    return 'email';
  });

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPw, setShowPw] = useState(false);
  const [pin, setPin] = useState('');
  const [restaurantId, setRestaurantId] = useState('');

  // Registration states
  const [regName, setRegName] = useState('');
  const [regEmail, setRegEmail] = useState('');
  const [regPassword, setRegPassword] = useState('');
  const [regRestName, setRegRestName] = useState('');
  const [regPhone, setRegPhone] = useState('');
  const [regAddress, setRegAddress] = useState('');
  const [regCurrency, setRegCurrency] = useState('INR');
  const [registering, setRegistering] = useState(false);

  const handleEmailLogin = async (e) => {
    e.preventDefault();
    const res = await loginWithEmail(email, password);
    if (!res.ok) toast.error(res.error);
    else toast.success('Welcome back!');
  };

  const handlePinKey = (key) => {
    if (pin.length >= 4) return;
    const next = pin + key;
    setPin(next);
    if (next.length === 4) submitPin(next);
  };

  const submitPin = async (p) => {
    if (!restaurantId.trim()) {
      toast.error('Enter Restaurant ID first');
      setPin('');
      return;
    }
    const res = await loginWithPin(restaurantId.trim(), p);
    if (!res.ok) {
      toast.error(res.error);
      setPin('');
    } else {
      toast.success('Welcome!');
    }
  };

  const handleRegister = async (e) => {
    e.preventDefault();
    if (!regName.trim() || !regEmail.trim() || !regPassword.trim() || !regRestName.trim()) {
      toast.error('Please fill in all required fields');
      return;
    }
    setRegistering(false);
    setRegistering(true);
    try {
      // 1. Create Firebase Auth user
      const cred = await createUserWithEmailAndPassword(auth, regEmail.trim(), regPassword);
      const uid = cred.user.uid;

      // 2. Prepare restaurant document reference (random ID generated by Firestore)
      const restDocRef = doc(collection(db, 'restaurants'));
      const newRestId = restDocRef.id;

      // 3. Write restaurant document with 'pending' status
      await setDoc(restDocRef, {
        name: regRestName.trim(),
        address: regAddress.trim(),
        phone: regPhone.trim(),
        currency: regCurrency,
        modes: ['pos'],
        taxConfig: { type: 'none' },
        createdAt: serverTimestamp(),
        ownerUid: uid,
        status: 'pending',
      });

      // 4. Write user profile document
      await setDoc(doc(db, 'users', uid), {
        uid: uid,
        name: regName.trim(),
        email: regEmail.trim(),
        role: 'admin',
        restaurantId: newRestId,
        createdAt: serverTimestamp(),
      });

      toast.success('Registration successful! Awaiting Super Admin approval.');
    } catch (err) {
      console.error(err);
      toast.error('Registration failed: ' + err.message);
    } finally {
      setRegistering(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-form-card">
        <Link to="/" className="login-back-home">
          ← Home
        </Link>
        <div className="login-card-header">
          <div className="login-logo">🍽️</div>
          <h2 className="login-card-title">
            {mode === 'email' ? t('adminLogin') : mode === 'pin' ? t('staffLogin') : 'Register Restaurant'}
          </h2>
          <p className="login-card-subtitle">
            {mode === 'email' 
              ? 'Sign in with your admin credentials' 
              : mode === 'pin' 
                ? 'Enter your restaurant ID and PIN' 
                : 'Start your modern restaurant POS journey today'}
          </p>
        </div>

        {/* Mode toggle */}
        <div className="login-mode-toggle">
          {[
            { m: 'email', label: '📧 Admin' },
            { m: 'pin', label: '🔢 Staff PIN' },
            { m: 'register', label: '🚀 Register' }
          ].map(item => (
            <button
              key={item.m}
              id={`login-mode-${item.m}`}
              onClick={() => { setMode(item.m); clearError(); setPin(''); }}
              className={`login-mode-btn ${mode === item.m ? 'active' : ''}`}
            >
              {item.label}
            </button>
          ))}
        </div>

        {error && (
          <div className="login-error-msg">{error}</div>
        )}

        {mode === 'email' ? (
          <form onSubmit={handleEmailLogin} className="login-form">
            <div className="form-group">
              <label className="form-label">Email</label>
              <input
                id="login-email"
                className="form-input"
                type="email"
                placeholder={t('emailPlaceholder')}
                value={email}
                onChange={e => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="form-group">
              <label className="form-label">Password</label>
              <div className="password-input-wrapper">
                <input
                  id="login-password"
                  className="form-input password-input"
                  type={showPw ? 'text' : 'password'}
                  placeholder={t('passwordPlaceholder')}
                  value={password}
                  onChange={e => setPassword(e.target.value)}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPw(!showPw)}
                  className="password-toggle-btn"
                >
                  {showPw ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
            </div>
            <button
              id="login-submit-btn"
              className="btn btn-primary btn-lg login-submit-btn"
              type="submit"
              disabled={loading}
            >
              {loading ? '...' : t('signIn')}
            </button>
          </form>
        ) : mode === 'pin' ? (
          <div className="login-form">
            <div className="form-group login-rest-id-group">
              <label className="form-label">Restaurant ID</label>
              <input
                id="login-restaurant-id"
                className="form-input"
                placeholder="e.g. my-restaurant or rest_abc123"
                value={restaurantId}
                onChange={e => setRestaurantId(e.target.value)}
              />
            </div>
            {/* PIN dots */}
            <div className="pin-dots">
              {[0,1,2,3].map(i => (
                <div key={i} className={`pin-dot ${i < pin.length ? 'filled' : ''}`} />
              ))}
            </div>
            {/* PIN pad */}
            <div className="pin-pad">
              {['1','2','3','4','5','6','7','8','9','','0','⌫'].map((k, i) => (
                <button
                  key={i}
                  id={k ? `pin-key-${k}` : undefined}
                  className={`pin-key ${k === '' ? 'empty' : ''}`}
                  onClick={() => {
                    if (k === '⌫') setPin(p => p.slice(0,-1));
                    else if (k) handlePinKey(k);
                  }}
                  disabled={loading}
                >
                  {k}
                </button>
              ))}
            </div>
            {loading && (
              <div className="login-verifying">
                Verifying...
              </div>
            )}
          </div>
        ) : (
          <form onSubmit={handleRegister} className="login-form register-form">
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Owner Name *</label>
                <input
                  id="reg-name"
                  className="form-input"
                  placeholder="Your Name"
                  value={regName}
                  onChange={e => setRegName(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Owner Email *</label>
                <input
                  id="reg-email"
                  className="form-input"
                  type="email"
                  placeholder="email@example.com"
                  value={regEmail}
                  onChange={e => setRegEmail(e.target.value)}
                  required
                />
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">Password *</label>
              <input
                id="reg-password"
                className="form-input"
                type="password"
                placeholder="Min 6 characters"
                value={regPassword}
                onChange={e => setRegPassword(e.target.value)}
                required
              />
            </div>

            <hr className="form-divider" />

            <div className="form-row unequal">
              <div className="form-group">
                <label className="form-label">Restaurant Name *</label>
                <input
                  id="reg-rest-name"
                  className="form-input"
                  placeholder="Delicious Cafe"
                  value={regRestName}
                  onChange={e => setRegRestName(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Currency *</label>
                <select
                  id="reg-rest-currency"
                  className="form-select"
                  value={regCurrency}
                  onChange={e => setRegCurrency(e.target.value)}
                  required
                >
                  {CURRENCY_OPTIONS.map(c => (
                    <option key={c.code} value={c.code}>{c.code}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Phone</label>
                <input
                  id="reg-phone"
                  className="form-input"
                  placeholder="+91..."
                  value={regPhone}
                  onChange={e => setRegPhone(e.target.value)}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Address</label>
                <input
                  id="reg-address"
                  className="form-input"
                  placeholder="City, Area"
                  value={regAddress}
                  onChange={e => setRegAddress(e.target.value)}
                />
              </div>
            </div>

            <button
              id="reg-submit-btn"
              className="btn btn-primary btn-lg login-submit-btn"
              type="submit"
              disabled={registering}
            >
              {registering ? 'Registering...' : 'Register Restaurant'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
